language: java
jdk: oraclejdk8

env:
  - COVERAGE=0.5 SERVICE=./monolithic/ui
  - COVERAGE=0.5 SERVICE=./monolithic/service/cart
  - COVERAGE=0.5 SERVICE=./monolithic/service/user
  - COVERAGE=0.5 SERVICE=./monolithic/repository/order
  - COVERAGE=0.5 SERVICE=./monolithic/repository/cart
  - COVERAGE=0.5 SERVICE=./monolithic/repository/product
  - COVERAGE=0.5 SERVICE=./monolithic/repository/user

install:
  - "./gradlew clean jar"
script:
  - ./gradlew -p $SERVICE check
after success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - COVERAGE=0.35 ./gradlew test jacocoTestCoverageVerification

after failure:
  - echo "errored"

deploy:
  provider: script
  script: echo 'WIP'
  on:
    all_branches: true